# Generated by Django 5.2.7 on 2025-10-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('1 mes', '1 mes'), ('1 bimestre', '1 bimestre'), ('1 trimestre', '1 trimestre'), ('1 semestre', '1 semestre'), ('1 año', '1 año')], max_length=20)),
                ('transporte', models.CharField(choices=[('Total', 'Total'), ('Parcial', 'Parcial'), ('Ninguno', 'Ninguno')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Próxima a vencer', 'Próxima a vencer'), ('Vencida', 'Vencida')], default='Activa', max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
