# Generated by Django 5.2.7 on 2025-10-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_matricula_canino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='canino',
            new_name='id_canino',
        ),
    ]
