# Generated by Django 5.2.7 on 2025-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('ENTRENADOR', 'Entrenador'), ('CLIENTE', 'Cliente')], max_length=20)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('fecha_vinculacion', models.DateField(blank=True, null=True)),
                ('foto', models.TextField(blank=True)),
                ('contrasena_hash', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
