# Generated by Django 5.2.7 on 2025-10-15 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canino',
            fields=[
                ('id_canino', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('raza', models.CharField(blank=True, max_length=150)),
                ('tamano', models.CharField(choices=[('Mini', 'Mini'), ('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Mediano', max_length=20)),
                ('edad_meses', models.IntegerField(blank=True, null=True)),
                ('carnet_vacunacion_url', models.TextField(blank=True)),
                ('desparasitado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caninos', to='users.usuario')),
            ],
        ),
    ]
