# Generated by Django 5.2.7 on 2025-12-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canino',
            name='edad_meses',
        ),
        migrations.AddField(
            model_name='canino',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
