# Generated by Django 5.2.7 on 2025-10-22 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('llegada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('motivo_salida', models.TextField(blank=True)),
                ('quien_retiro', models.CharField(blank=True, max_length=200)),
                ('tipo_llegada', models.CharField(choices=[('Ruta', 'Ruta'), ('Propietario', 'Propietario')], max_length=20)),
                ('id_canino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='canines.canino')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionFisica',
            fields=[
                ('id_condicion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pelaje_piel', models.CharField(blank=True, max_length=255)),
                ('color_mucosas', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('id_canino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='canines.canino')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condiciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aprendizaje',
            fields=[
                ('id_aprendizaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('obediencia', models.SmallIntegerField()),
                ('sociabilidad', models.SmallIntegerField()),
                ('conciencia', models.SmallIntegerField()),
                ('actividad', models.SmallIntegerField()),
                ('estado_animo', models.SmallIntegerField()),
                ('id_canino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes', to='canines.canino')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendizajes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_canino', 'mes', 'anio')},
            },
        ),
    ]
