# Generated by Django 5.2.7 on 2025-10-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicionfisica',
            options={'verbose_name': 'Condición física', 'verbose_name_plural': 'Condición física'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='llegada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de llegada'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='motivo_salida',
            field=models.TextField(blank=True, verbose_name='Motivo de salida'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='quien_retiro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Quién retiró'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='tipo_llegada',
            field=models.CharField(choices=[('Ruta', 'Ruta'), ('Propietario', 'Propietario')], max_length=20, verbose_name='Tipo de llegada'),
        ),
    ]
