# Generated by Django 5.2.7 on 2025-12-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_condicionfisica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='llegada',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
